# Generated by Django 5.1.4 on 2024-12-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nhanvien_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Oder_nhanvien',
            new_name='Order_nhanvien',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='oder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='order_nhanvien',
            old_name='oder',
            new_name='order',
        ),
    ]
