# Generated by Django 5.1.4 on 2024-12-10 05:36

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_nhanvien',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order_nhanvien',
            name='thoigianbatdau',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order_nhanvien',
            name='thoigianthue',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
