# Generated by Django 5.1.4 on 2024-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_nhanvien_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_nhanvien',
            name='thoigianbatdau',
        ),
        migrations.RemoveField(
            model_name='order_nhanvien',
            name='thoigianthue',
        ),
        migrations.AddField(
            model_name='order_nhanvien',
            name='dientich',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
