# Generated by Django 5.1.4 on 2024-12-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='category',
            field=models.ManyToManyField(related_name='nhanvien', to='app.category'),
        ),
    ]
