# Generated by Django 5.1.4 on 2024-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_nhanvien_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='price',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
