# Generated by Django 5.1.4 on 2024-12-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_nhanvien_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
